apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImNISmhhbmRoYkRFek1qYzZVSEpoYW5kaGJFQXgiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
