apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    type: aws-ebs-volume 
  name: ebs-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: jenkins-root-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
