apiVersion: v1
kind: Pod
metadata:
  name: privatetomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: mytomcat
    image: prajwal1327/mytomcat:1.1.6
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-cluster
spec:
  selector:
    app: tomcat
  type: LoadBalancer
  ports:
    - name: tomcat
      protocol: TCP
      targetPort: 8080
      port: 8080
