apiVersion: v1
kind: Pod
metadata: 
  name: tomcat-nginx
  namespace: devlopment-nms
  labels:
    app: tomcat1
spec:
  containers:
    - name: tomcat
      image: prajwal1327/mytomcat:1.1.6
    - name: nginx
      image: nginx:1.14.2
